apiVersion: v1
kind: Service
metadata:
  name: docker-eks-demo-service
  namespace: eks-docker-app
  labels:
    app: docker-eks-demo
spec:
  selector:
    app: docker-eks-demo
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
